global:
  iam_role_arn_aws: null
  enabled_aws: true

deploymentRuntimeConfig:
  enabled: true
  metadata:
    name: "aws-runtime-config"
    annotations: {}
    labels: {}
  spec:
    deploymentTemplate:
      spec:
        selector: {}
        template:
          spec:
            containers:
              - name: package-runtime
                args:
                - --debug
            securityContext:
              fsGroup: 2000
    serviceAccountTemplate:
      metadata:
        annotations: {}
        labels: {}
        name: provider-aws

provider:
  enabled: true
  metadata:
    name: "provider-aws"
    iam_role_arn: null
    annotations: {}
    labels: {}
  package:
    registry: xpkg.upbound.io/crossplane-contrib/provider-aws
    version: "v0.45.2"

providerConfig:
  enabled: true
  metadata:
    name: "aws-provider-config"
    annotations: {}
    labels: {}
  spec:
    credentials:
      source: InjectedIdentity
